Repository BHoM/IES_Toolkit, pull requests merged in 2020-06, with the labels that each got.

#134 Using Air as PanelType
  IES_Engine/Convert/Environment/Space.cs
Labels: type:feature

#136 Update referencing and post build
  IES_Adapter/IES_Adapter.csproj
  IES_Engine/IES_Engine.csproj
  IES_oM/IES_oM.csproj
Labels: type:external-api-changes

#139 Update namespace
  IES_Adapter/CRUD/Create.cs
  IES_Adapter/CRUD/Read.cs
  IES_Adapter/IESAdapter.cs
  IES_Engine/Convert/Environment/Opening.cs
  IES_Engine/Convert/Environment/OpeningType.cs
  IES_Engine/Convert/Environment/Panel.cs
  IES_Engine/Convert/Environment/Space.cs
  IES_Engine/Convert/Geometry/Point.cs
  IES_Engine/Create/SettingsIES.cs
  IES_Engine/Modify/RepairOpening.cs
  IES_Engine/Modify/RoundedPoint.cs
  IES_Engine/Query/BottomLeft.cs
  IES_Engine/Query/BottomRight.cs
  IES_Engine/Query/IsLeft.cs
  IES_Engine/Query/Polyline.cs
  IES_Engine/Query/TopRight.cs
  IES_Engine/Versioning_32.json
Labels: type:compliance

#140 Migrate code to Environment_Engine
  IES_Engine/IES_Engine.csproj
  IES_Engine/Query/BottomLeft.cs
  IES_Engine/Query/BottomRight.cs
  IES_Engine/Query/IsLeft.cs
  IES_Engine/Query/TopRight.cs
Labels: type:compliance
